apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector:
      app: grafana
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1 # tells deployment to run 1 pod replica
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        imagePullPolicy: Never
        image: 'grafana:ael-ghem'
        livenessProbe:
          exec:
            command:
            - cat
            - /liveness/live
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 3000

