apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec: 
  selector:
      app: mysql
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1 # tells deployment to run 1 pod replica
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        imagePullPolicy: Never
        image: 'mysql:ael-ghem'
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: pv-storage
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        - name:  MYSQL_USER
          value: "ael-ghem"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "wordpress"
        ports:
        - containerPort: 3306
      volumes:
      - name: pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim




