
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec: 
  selector:
      app: nginx
  type: LoadBalancer
  loadBalancerIP:
    192.168.2.5
  ports:
  - name: http
    port: 80
    targetPort: 80
