apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 # tells deployment to run 1 pod replica
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        imagePullPolicy: Never
        image: 'nginx:ael-ghem'
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
