
apiVersion: v1
kind: Service
metadata:
  name: ft-nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30001
  - name: https
    port: 443
    targetPort: https
    nodePort: 30002
  - name: ssh
    port: 22
    targetPort: ssh
    nodePort: 30003
  selector:
    app: ft-nginx
  type: LoadBalancer